# Generated by Django 3.2.5 on 2022-08-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
