# Generated by Django 3.2.5 on 2022-08-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Bill_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Bill_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Cash', 'Cash'), ('Debit', 'Debit')], default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billinsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_number', models.IntegerField()),
                ('Bill_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('sub_total', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('paid', models.BooleanField()),
                ('invoice_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('product_id_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT')], max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('is_received', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_order', models.DateField()),
                ('made_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('order_options', models.CharField(choices=[('TP', 'Telephone'), ('Post', 'POST'), ('fax', 'Fax')], max_length=50)),
                ('Is_pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Price')),
                ('evaporation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Evaporation Allowance')),
                ('brought_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Brought Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('availability', models.IntegerField(default=0)),
                ('traffic', models.IntegerField(default=0)),
                ('next_arrival', models.DateField(blank=True, default='', null=True)),
                ('category_type', models.CharField(choices=[('GOODS', 'Goods'), ('FUEL', 'Fuel')], default='', max_length=50)),
                ('css_color_code', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger'), ('warning', 'warning')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('worker', models.CharField(blank=True, max_length=50, null=True)),
                ('PreReading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EndReading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Operator_ON', models.CharField(blank=True, max_length=50, null=True)),
                ('Operator_OFF', models.CharField(blank=True, max_length=50, null=True)),
                ('Is_On', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_product', to='POS.product')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_address1', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, choices=[('LAND1', 'LAND1'), ('LAND2', 'LAND2'), ('MOBILE', 'MOBILE')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('FUEL', 'FUEL'), ('GOODS', 'GOODS')], max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('pre_order_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_products', to='POS.product')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('Station_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Is_On', models.BooleanField(default=False)),
                ('meter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Station_Date', models.DateTimeField(auto_now=True)),
                ('Station_Fuel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_fuel', to='POS.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Money',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='POS.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_Name', models.CharField(blank=True, max_length=50)),
                ('PreReading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EndReading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('worker', models.CharField(max_length=50)),
                ('Operator_ON', models.CharField(max_length=50)),
                ('Operator_OFF', models.CharField(blank=True, max_length=50, null=True)),
                ('Shift_On_Date', models.DateTimeField(auto_now=True)),
                ('Shift_Off_Date', models.DateTimeField(auto_now=True)),
                ('Is_Using', models.BooleanField(default=True)),
                ('Pre_Money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Short_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Shift_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='POS.shift')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.station'),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('order_item_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Is_received', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='POS.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='POS.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('NetAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
        migrations.CreateModel(
            name='Billing_Detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Bill_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POS.bill')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='POS.product')),
            ],
        ),
    ]
