# Generated by Django 3.2.5 on 2021-09-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('sub_total', models.IntegerField()),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Cash', 'Cash'), ('Debit', 'Debit')], default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('order_level', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pre Order Level')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('invoice_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='POS.invoice')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='POS.products')),
            ],
        ),
    ]
