# Generated by Django 3.2.5 on 2021-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('FUEL', 'Fuel')], default='', max_length=50),
        ),
    ]
