# Generated by Django 3.2.5 on 2022-01-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=50, null=True)),
                ('PreReading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EndReading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Operator_ON', models.CharField(blank=True, max_length=50, null=True)),
                ('Operator_OFF', models.CharField(blank=True, max_length=50, null=True)),
                ('Is_On', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_product', to='POS.product')),
                ('shift_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.station')),
            ],
        ),
    ]
