# Generated by Django 3.2.5 on 2021-10-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_product_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('pre_order_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.product')),
            ],
        ),
    ]
