# Generated by Django 3.2.5 on 2021-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20211018_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing_detail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
