# Generated by Django 3.2.5 on 2022-01-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
