# Generated by Django 3.2.5 on 2021-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20210917_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
