# Generated by Django 3.2.5 on 2022-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20220717_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='css_color_code',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger'), ('warning', 'warning')], default='', max_length=100),
        ),
    ]
