# Generated by Django 3.2.5 on 2021-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20211018_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_number',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
