# Generated by Django 3.2.5 on 2021-10-28 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('date_of_order', models.DateTimeField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('made_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('order_options', models.CharField(choices=[('TP', 'Telephone'), ('Post', 'POST'), ('fax', 'Fax')], max_length=50)),
                ('Is_pending', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
    ]
