# Generated by Django 3.2.5 on 2022-01-26 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_alter_shift_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_Name', models.CharField(blank=True, max_length=50)),
                ('PreReading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EndReading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('worker', models.CharField(max_length=50)),
                ('Operator_ON', models.CharField(max_length=50)),
                ('Operator_OFF', models.CharField(blank=True, max_length=50, null=True)),
                ('Shift_On_Date', models.DateTimeField(auto_now=True)),
                ('Shift_Off_Date', models.DateTimeField(auto_now=True)),
                ('Is_Using', models.BooleanField(default=True)),
                ('Pre_Money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Short_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Shift_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='POS.shift')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
    ]
