# Generated by Django 3.2.5 on 2021-09-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_alter_billing_details_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='Bill_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
