# Generated by Django 3.2.5 on 2022-07-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_product_css_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
