# Generated by Django 3.2.5 on 2022-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20220801_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
