# Generated by Django 3.2.5 on 2022-01-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_shift_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_money',
            name='shift',
        ),
        migrations.AddField(
            model_name='shift_money',
            name='Shift_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shift_money', to='POS.shift'),
        ),
        migrations.AddField(
            model_name='shift_money',
            name='shift_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
