# Generated by Django 3.2.5 on 2021-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_auto_20210923_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billinsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_number', models.IntegerField()),
                ('Bill_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('sub_total', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('paid', models.BooleanField()),
                ('invoice_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('product_id_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('lives_in', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
