# Generated by Django 3.2.5 on 2021-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
