# Generated by Django 3.2.5 on 2022-07-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_product_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
    ]
