# Generated by Django 3.2.5 on 2021-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
