# Generated by Django 3.2.5 on 2022-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_alter_product_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
