# Generated by Django 3.2.5 on 2022-01-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_auto_20220126_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_money',
            name='Shift_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_money', to='POS.shift'),
        ),
    ]
