# Generated by Django 3.2.5 on 2021-10-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_alter_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('order_item_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
    ]
