# Generated by Django 3.2.5 on 2021-09-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_billinsert_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
