# Generated by Django 3.2.5 on 2021-10-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_detail',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
