# Generated by Django 3.2.5 on 2021-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_auto_20210926_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
            ],
        ),
    ]
