# Generated by Django 3.2.5 on 2021-10-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_auto_20211028_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoive_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT')], max_length=50)),
                ('is_received', models.BooleanField(default=True)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.order')),
            ],
        ),
    ]
