# Generated by Django 3.2.5 on 2022-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_alter_product_arrival_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='arrival_date',
            new_name='Date_of_arival',
        ),
    ]
