# Generated by Django 3.2.5 on 2022-01-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_alter_shift_money_shift_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_money',
            name='Shift_ID',
        ),
        migrations.AddField(
            model_name='shift_money',
            name='shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='POS.shift'),
        ),
    ]
