# Generated by Django 3.2.5 on 2021-09-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
