# Generated by Django 3.2.5 on 2022-08-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_rename_arrival_date_product_date_of_arival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Date_of_arival',
        ),
    ]
