# Generated by Django 3.2.5 on 2022-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_alter_product_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(choices=[('NOT ENOUGH', 'NOT ENOUGH'), ('ENOUGH', 'ENOUGH')], max_length=100, null=True),
        ),
    ]
