# Generated by Django 3.2.5 on 2022-01-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_auto_20220126_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_money',
            name='shift_Name',
        ),
    ]
