# Generated by Django 3.2.5 on 2021-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
