# Generated by Django 3.2.5 on 2022-07-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_alter_product_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
