# Generated by Django 3.2.5 on 2021-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_studentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
