# Generated by Django 3.2.5 on 2021-10-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_invoice_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_level',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Invoice_Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS.product')),
            ],
        ),
    ]
