# Generated by Django 3.2.5 on 2022-08-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_remove_product_date_of_arival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
