# Generated by Django 3.2.5 on 2022-01-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_remove_shift_money_shift_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='Operator_OFF',
        ),
        migrations.RemoveField(
            model_name='station',
            name='Operator_ON',
        ),
        migrations.AddField(
            model_name='station',
            name='Station_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='station',
            name='meter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
