# Generated by Django 3.2.5 on 2022-07-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20220727_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
    ]
