# Generated by Django 3.2.5 on 2022-01-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20220130_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Station_Fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_fuel', to='POS.product'),
        ),
    ]
