# Generated by Django 3.2.5 on 2022-08-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_product_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='arrival_date',
        ),
    ]
