# Generated by Django 3.2.5 on 2021-10-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20211028_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoive_number',
            new_name='invoice_number',
        ),
    ]
