# Generated by Django 3.2.5 on 2021-10-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_rename_invoive_number_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='POS.order'),
        ),
    ]
