# Generated by Django 3.2.5 on 2021-09-30 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
