# Generated by Django 3.2.5 on 2022-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_remove_product_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='next_arrival',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
