# Generated by Django 3.2.5 on 2021-10-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_bills_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
