# Generated by Django 3.2.5 on 2021-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_alter_order_item_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateField(),
        ),
    ]
