# Generated by Django 3.2.5 on 2021-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0012_alter_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
