# Generated by Django 3.2.5 on 2021-11-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0013_alter_order_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
