# Generated by Django 3.2.5 on 2021-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0014_alter_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='Is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_item',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
