# Generated by Django 3.2.5 on 2021-11-04 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0015_auto_20211104_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='POS.product'),
        ),
    ]
