# Generated by Django 3.2.5 on 2021-11-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0016_alter_order_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brought_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Brought Price'),
        ),
    ]
