# Generated by Django 3.2.5 on 2021-11-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0017_product_brought_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_address1', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, choices=[('LAND1', 'LAND1'), ('LAND2', 'LAND2'), ('MOBILE', 'MOBILE')], default='', max_length=50, null=True)),
            ],
        ),
    ]
