# Generated by Django 3.2.5 on 2021-11-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0018_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='POS.supplier'),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('FUEL', 'FUEL'), ('GOODS', 'GOODS')], default='fuel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT')], default='CASH', max_length=50),
        ),
    ]
