# Generated by Django 3.2.5 on 2021-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0019_auto_20211107_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
    ]
