# Generated by Django 3.2.5 on 2021-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0020_auto_20211107_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_items',
            old_name='amount',
            new_name='NetAmount',
        ),
        migrations.AddField(
            model_name='invoice_items',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_items',
            name='extAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_items',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
