# Generated by Django 3.2.5 on 2021-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0021_auto_20211110_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_name',
            field=models.CharField(max_length=50),
        ),
    ]
