# Generated by Django 3.2.5 on 2021-11-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0022_alter_invoice_supplier_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice_Items',
            new_name='InvoiceItems',
        ),
    ]
