# Generated by Django 3.2.5 on 2021-11-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0023_rename_invoice_items_invoiceitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItems',
            new_name='InvoiceItem',
        ),
    ]
