# Generated by Django 3.2.5 on 2021-11-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0024_rename_invoiceitems_invoiceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
