# Generated by Django 3.2.5 on 2021-11-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0026_invoiceitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItem',
            new_name='Invoice_Item',
        ),
    ]
