# Generated by Django 3.2.5 on 2021-11-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0027_rename_invoiceitem_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='NetAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='extAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
