# Generated by Django 3.2.5 on 2021-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0030_product_evap_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Evap_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Evaporation Allowance'),
        ),
    ]
